#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

MSG="$1"

if ! grep -qE "(init|chore|feat|fix|refactor|docs): " "$MSG";then
    cat "$MSG"
    echo "Your commit message must corresponding commit requirements!'"
    exit 1
fi